services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: spring
      POSTGRES_USER: spring
      POSTGRES_PASSWORD: spring
    container_name: db_hibernet
    ports:
      - "5432:5432"